# Use the official MongoDB image as the base image
FROM mongo:latest

# Copy the MongoDB dump into the container
COPY ./dump /dump

# Add a script to restore the database from the dump
COPY mongo_restore.sh /docker-entrypoint-initdb.d/

# Make the restore script executable
RUN chmod +x /docker-entrypoint-initdb.d/mongo_restore.sh