# Use the official MongoDB image as the base image
FROM mongo:6

# Create dump mount point
RUN mkdir -p /dump

# Add a script to restore the database from the dump (runs on first init)
COPY mongo_restore.sh /docker-entrypoint-initdb.d/

# Make the restore script executable
RUN chmod +x /docker-entrypoint-initdb.d/mongo_restore.sh