const { BonusTemplate } = require('../../../app/models/bonus/template');

async function findOrCreateHistoricalTemplate({
    code,
    name,
    category,
    periodicity = 'quarterly',
    taxConfig,
    calculationOverrides = {}
}) {
    let template = await BonusTemplate.findOne({ code, isHistoricalTemplate: true });
    if (template) return template;

    const calc = Object.assign({
        fixedAmount: 0,
        rate: 0,
        partsConfig: { defaultParts: 1 }
    }, calculationOverrides);

    // Align with allowed enum for subType (remise | ift) only when category is without_parts
    if (category === 'without_parts') {
        if (!calc.subType) {
            calc.subType = 'remise';
        } else if (!['remise', 'ift'].includes(calc.subType)) {
            calc.subType = 'remise';
        }
    } else {
        // Avoid sending subType for categories where it's not needed/validated
        delete calc.subType;
    }

    template = await BonusTemplate.create({
        code,
        name,
        description: 'Template generated by Excel migration',
        category,
        periodicity,
        isActive: false,
        isHistoricalTemplate: true,
        calculationConfig: calc,
        taxConfig
    });

    return template;
}

module.exports = {
    findOrCreateHistoricalTemplate
};
